[package]
name = "kcp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio_kcp = { path = "../tokio_kcp" }
tokio = { version = "1.11", features = ["full"] }
env_logger = "0.11.5"
log = "0.4.22"
byte_string = "1"
