[package]
name = "kcp_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio_kcp = { path = "../tokio_kcp" }
tokio = { version = "1.11", features = ["full"] }
env_logger = "0.11.5"
anyhow = "1.0.94"
bytes = "1.9.0"